In [2]:
from keras.datasets import mnist
from keras.utils import to_categorical

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [5]:
x_train.shape

(60000, 28, 28)

In [6]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
# Предобработка данных
x_train = x_train.reshape((x_train.shape[0], -1)).astype('float32') / 255.0
x_test = x_test.reshape((x_test.shape[0], -1)).astype('float32') / 255.0
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [9]:
x_train.shape

(60000, 784)

In [10]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [11]:
from keras.models import Sequential
from keras.layers import Dense

# Создание модели
model = Sequential()
model.add(Dense(128, input_shape=(784,), activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [12]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [13]:
model.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10


1500/1500 [==============================] - 7s 4ms/step - loss: 0.2623 - accuracy: 0.9243 - val_loss: 0.1459 - val_accuracy: 0.9577
Epoch 2/10
1500/1500 [==============================] - 5s 4ms/step - loss: 0.1136 - accuracy: 0.9665 - val_loss: 0.1106 - val_accuracy: 0.9672
Epoch 3/10
1500/1500 [==============================] - 8s 5ms/step - loss: 0.0785 - accuracy: 0.9756 - val_loss: 0.1023 - val_accuracy: 0.9690
Epoch 4/10
1500/1500 [==============================] - 6s 4ms/step - loss: 0.0580 - accuracy: 0.9817 - val_loss: 0.0937 - val_accuracy: 0.9729
Epoch 5/10
1500/1500 [==============================] - 6s 4ms/step - loss: 0.0449 - accuracy: 0.9854 - val_loss: 0.1079 - val_accuracy: 0.9699
Epoch 6/10
1500/1500 [==============================] - 7s 5ms/step - loss: 0.0369 - accuracy: 0.9879 - val_loss: 0.0979 - val_accuracy: 0.9735
Epoch 7/10
1500/1500 [==============================] - 6s 4ms/step - loss: 0.0290 - accuracy: 0.9905 - val_loss: 0.1130 - val_accurac

In [14]:
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f'Test result: {test_loss, test_acc}')

313/313 [==============================] - 1s 3ms/step - loss: 0.1197 - accuracy: 0.9721
Test result: (0.11969930678606033, 0.972100019454956)


In [15]:
hist = model.fit(x_train, y_train, epochs=3, batch_size=64, validation_split=0.2)

Epoch 1/3
750/750 [==============================] - 5s 6ms/step - loss: 0.0059 - accuracy: 0.9983 - val_loss: 0.1063 - val_accuracy: 0.9782
Epoch 2/3
750/750 [==============================] - 4s 6ms/step - loss: 0.0026 - accuracy: 0.9995 - val_loss: 0.1056 - val_accuracy: 0.9790
Epoch 3/3
750/750 [==============================] - 4s 6ms/step - loss: 0.0017 - accuracy: 0.9997 - val_loss: 0.1189 - val_accuracy: 0.9769


In [18]:
hist.history['accuracy']

[0.9983124732971191, 0.9994791746139526, 0.9997291564941406]

In [28]:
x_test[3] * 255

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,  11., 150., 253., 202.,  31.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   

In [27]:
y_test[3]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [24]:
import numpy as np

In [26]:
model.predict(np.array([x_test[3]]))

1/1 [==============================] - 0s 66ms/step


array([[1.0000000e+00, 5.2832847e-13, 7.4402526e-11, 1.6595639e-13,
        2.4564201e-14, 3.6019356e-15, 1.8585454e-09, 2.7845952e-09,
        4.2733249e-16, 4.3519319e-10]], dtype=float32)